from smart_car_decision.map_assets import save_occupancy_snapshot


def test_save_occupancy_snapshot_writes_pgm_and_yaml(tmp_path):
    snapshot = {
        "info": {
            "width": 2,
            "height": 2,
            "resolution": 0.05,
            "origin": {"x": -1.0, "y": -2.0, "yaw": 0.0},
        },
        "data": [-1, 0, 50, 100],
    }

    result = save_occupancy_snapshot(snapshot, tmp_path, stem="test_map")

    assert result["ok"] is True
    yaml_path = tmp_path / "test_map.yaml"
    pgm_path = tmp_path / "test_map.pgm"
    assert yaml_path.exists()
    assert pgm_path.exists()
    assert "resolution: 0.05" in yaml_path.read_text(encoding="utf-8")
    assert pgm_path.read_bytes().startswith(b"P5\n# Generated by smart_car_decision\n2 2\n255\n")
